### ISSUE TITLE
insert sessions to storage even when empty

### ISSUE THREAD

**Issue by kwladyka** [luminus-framework/jdbc-ring-session#13]
Not 100% sure if it is `wrap-session` issue or `jdbc-store`, but I think it is responsibility of `jdbc-store`.

```
(def app-stateless
  (-> handler
      (wrap-keyword-params {:parse-namespaces? true})
      (wrap-restful-format)
      (add-headers)))

(def app
  (-> app-stateless
      (wrap-idle-session-timeout {:timeout 3600
                                  :timeout-handler app-stateless})
      (wrap-session {:store (jdbc-store postgres/db {:table :sessions})
                     :cookie-name "auth-session"
                     :cookie-attrs {:http-only true
                                    :same-site :lax
                                    ;:secure true ; https
                                    ; :domain "redjar.biz"
                                    ;:max-age 1800
                                    }})))
```

So it makes new session in storage each time for every request.
`curl -i -X OPTIONS http://localhost:8080/authentication` make new session in storage.
I guess in code miss check if session is `nil` for `insert` to DB.

It makes a lot of unnecessary sessions in DB.

BTW Additional it could delete session from storage, when response return `:session nil` for already existed `:session`. It can remember if it was exited during request and check during response.

**Comment by yogthos** [comment]
The library mirrors the behavior of the [memory store](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/session/memory.clj) in Ring core. That implementation creates new sessions when the `key` is `nil`:

```clojure
(write-session [_ key data]
    (let [key (or key (str (UUID/randomUUID)))]
      (swap! session-map assoc key data)
key))
```

The session cleaning has to be done outside the request response cycle otherwise you will have a memory leak when the client disconnects abruptly, such as the user closing the browser tab. In that scenario you'll end up with a stale session in the database. This is why the cleaner thread is needed to clean stale sessions in the background at an interval.

**Comment by kwladyka** [comment]
Hmm... do you see any reasons why somebody want to add empty sessions to DB? Maybe it is done for memory storage, because it is mainly for developing purpose. I am trying to find reasons why it can be intentional, but I can't. Logic says me library shouldn't add nil sessions, also update session to nil (in ring) should remove session instead of update to nil (in JDBC). But maybe I miss something not obviously.

**Comment by yogthos** [comment]
Ring default behavior is to create a session by default as opposed to explicitly. In most cases this won't be an issue, an empty session will be created, and then it's available for use from then on. The cleaner thread will periodically remove stale sessions, and you have to do this regardless of whether you create a session on connect or at a later time. So, I don't really see this behavior as problematic since the clean up routine ensures that old sessions are cleaned up periodically.

I think if you want a different behavior that should be handled by the session middleware as opposed to the session store itself. You could either extend the functionality of the default middleware, or make your own version with a different behavior.
